"""
Sends the daily email digest (top gainers, top volume spikes, market news)
to subscribers stored in Firestore's `email_subscribers` collection.

Reuses data already generated by the scanner run — no recomputation, no
extra network calls beyond Resend itself and one Firestore read:
  - data/daily_digest.json  → top_gainers / top_volume (same as the homepage panel)
  - data/market_news.json / market_news_cn.json → market headlines (EN / CN, already translated)

Zero-op safe: if RESEND_API_KEY or FIREBASE_SERVICE_ACCOUNT_JSON aren't set,
prints a message and exits 0 without sending anything, so this can be wired
into scanner.yml before either secret exists without breaking the workflow.
"""

import json
import os
import sys
import time

import requests

RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "").strip()
FROM_ADDRESS = "Baizora Daily Digest <digest@baizora.com>"
UNSUB_BASE = "https://us-central1-baizora.cloudfunctions.net/api/unsubscribe"
SEND_PACE_SEC = 0.3  # stay well under Resend's per-second rate limit


def fmt_pct(v):
    sign = "+" if v >= 0 else ""
    return f"{sign}{v:.2f}%"


def load_json(path, default=None):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return default


def build_movers_rows(movers, pct_key, color_key=None):
    rows = []
    for m in movers:
        pct = m.get(pct_key)
        if pct is None:
            continue
        color = "#22c55e" if pct >= 0 else "#ef4444"
        rows.append(f"""
        <tr>
          <td style="padding:6px 0;font-family:monospace;font-size:13px;color:#60a5fa;font-weight:600;">{m['ticker']}</td>
          <td style="padding:6px 8px;font-size:12px;color:#94a3b8;">{m.get('name','')}</td>
          <td style="padding:6px 0;font-family:monospace;font-size:13px;color:{color};font-weight:600;text-align:right;">{fmt_pct(pct)}</td>
        </tr>""")
    return "".join(rows)


def build_news_rows(items, title_key="title", n=5):
    rows = []
    for it in items[:n]:
        rows.append(f"""
        <tr><td style="padding:8px 0;border-bottom:1px solid #1e293b;">
          <a href="{it['link']}" style="color:#e2e8f0;text-decoration:none;font-size:13px;line-height:1.4;">{it.get(title_key, it.get('title',''))}</a>
          <div style="color:#64748b;font-size:11px;margin-top:2px;">{it.get('source','')}</div>
        </td></tr>""")
    return "".join(rows)


def render_email(lang, digest, news_items, unsub_link):
    is_cn = lang == "zh"
    t = {
        "subject":  ("每日市场简报 — " if is_cn else "Baizora Daily Digest — ") + digest.get("date", ""),
        "heading":  "每日市场简报" if is_cn else "Today's Market Briefing",
        "gainers":  "涨幅榜" if is_cn else "Top Gainers",
        "volume":   "成交量异动" if is_cn else "Volume Spikes",
        "news":     "市场新闻" if is_cn else "Market News",
        "footer":   "您收到此邮件是因为您在 baizora.com 订阅了每日简报。" if is_cn else "You're receiving this because you subscribed to the daily digest at baizora.com.",
        "unsub":    "取消订阅" if is_cn else "Unsubscribe",
        "view":     "在网站上查看完整数据 →" if is_cn else "View full data on the site →",
    }
    gainers_rows = build_movers_rows(digest.get("top_gainers", []), "chg1d")
    volume_rows  = build_movers_rows(digest.get("top_volume", []), "volchg")
    news_rows    = build_news_rows(news_items, title_key=("title_cn" if is_cn else "title"))

    html = f"""<!doctype html>
<html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#060d1f;font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#060d1f;padding:24px 0;">
<tr><td align="center">
<table width="560" cellpadding="0" cellspacing="0" style="background:#0d1e3d;border-radius:16px;overflow:hidden;">
  <tr><td style="padding:24px 28px;border-bottom:1px solid #1e293b;">
    <span style="font-family:Georgia,serif;font-size:20px;color:#f8fafc;">Baiz<span style="color:#3b82f6;">ora</span></span>
    <div style="color:#64748b;font-size:12px;margin-top:4px;">{t['heading']} · {digest.get('date','')}</div>
  </td></tr>
  <tr><td style="padding:20px 28px;">
    <div style="color:#60a5fa;font-size:11px;letter-spacing:0.1em;text-transform:uppercase;margin-bottom:8px;">{t['gainers']}</div>
    <table width="100%" cellpadding="0" cellspacing="0">{gainers_rows}</table>
  </td></tr>
  <tr><td style="padding:0 28px 20px;">
    <div style="color:#60a5fa;font-size:11px;letter-spacing:0.1em;text-transform:uppercase;margin-bottom:8px;">{t['volume']}</div>
    <table width="100%" cellpadding="0" cellspacing="0">{volume_rows}</table>
  </td></tr>
  <tr><td style="padding:0 28px 20px;">
    <div style="color:#60a5fa;font-size:11px;letter-spacing:0.1em;text-transform:uppercase;margin-bottom:8px;">{t['news']}</div>
    <table width="100%" cellpadding="0" cellspacing="0">{news_rows}</table>
  </td></tr>
  <tr><td style="padding:16px 28px;border-top:1px solid #1e293b;">
    <a href="https://baizora.com{'/index_cn.html' if is_cn else ''}" style="color:#60a5fa;font-size:12px;text-decoration:none;">{t['view']}</a>
  </td></tr>
  <tr><td style="padding:16px 28px;background:#0a1628;">
    <div style="color:#475569;font-size:11px;line-height:1.6;">{t['footer']} <a href="{unsub_link}" style="color:#475569;">{t['unsub']}</a></div>
  </td></tr>
</table>
</td></tr>
</table>
</body></html>"""
    return t["subject"], html


def get_subscribers():
    from google.cloud import firestore
    from google.cloud.firestore_v1.base_query import FieldFilter
    db = firestore.Client()
    docs = db.collection("email_subscribers").where(filter=FieldFilter("unsubscribed", "==", False)).stream()
    return [d.to_dict() for d in docs]


def send_via_resend(to_email, subject, html):
    resp = requests.post(
        "https://api.resend.com/emails",
        headers={"Authorization": f"Bearer {RESEND_API_KEY}", "Content-Type": "application/json"},
        json={"from": FROM_ADDRESS, "to": [to_email], "subject": subject, "html": html},
        timeout=15,
    )
    return resp.status_code, resp.text


def main():
    if not RESEND_API_KEY:
        print("send_daily_digest: RESEND_API_KEY not set — skipping (not yet configured).")
        return
    if not os.environ.get("GOOGLE_APPLICATION_CREDENTIALS"):
        print("send_daily_digest: GOOGLE_APPLICATION_CREDENTIALS not set — skipping (not yet configured).")
        return

    digest = load_json("data/daily_digest.json")
    if not digest:
        print("send_daily_digest: data/daily_digest.json missing — nothing to send.")
        return

    news_en = load_json("data/market_news.json", {"items": []})["items"]
    news_cn = load_json("data/market_news_cn.json", {"items": []})["items"]

    try:
        subscribers = get_subscribers()
    except Exception as e:
        print(f"send_daily_digest: failed to read subscribers from Firestore — {e}")
        return

    if not subscribers:
        print("send_daily_digest: no active subscribers.")
        return

    sent, failed = 0, 0
    for sub in subscribers:
        email = sub.get("email")
        token = sub.get("unsubToken")
        locale = sub.get("locale", "en")
        if not email or not token:
            continue
        unsub_link = f"{UNSUB_BASE}?email={email}&token={token}"
        news_items = news_cn if locale == "zh" else news_en
        subject, html = render_email("zh" if locale == "zh" else "en", digest, news_items, unsub_link)
        try:
            status, body = send_via_resend(email, subject, html)
            if status < 300:
                sent += 1
            else:
                failed += 1
                print(f"  {email}: Resend returned {status} — {body[:200]}")
        except Exception as e:
            failed += 1
            print(f"  {email}: send error — {e}")
        time.sleep(SEND_PACE_SEC)

    print(f"send_daily_digest: sent {sent}, failed {failed}, total subscribers {len(subscribers)}")


if __name__ == "__main__":
    main()
